### ISSUE TITLE
retained flag for status

### ISSUE THREAD

**Issue by luxus** [kkckkc/ZWayMqttEndpoint#4]
would be great if the messages would have a retained flag. i using home-assistant and when i reload it it don't get any states because they just got written on updates

**Comment by kkckkc** [comment]
Yes, that would be a good idea. 

Not sure what you are trying to achieve, but if it's just about keeping the statuses of your devices across home-assistant restarts, then I've solved it using the following automation rule

```
- alias: 'HASS Startup'
  trigger:
     platform: event
     event_type: homeassistant_start
  action:
     service: mqtt.publish
     data:
        payload_template: status
        topic: zway/status
```

Essentially it queries status on startup
