### ISSUE TITLE
Howto command my Fibaro Wall Plug

### ISSUE THREAD

**Issue by mny24** [kkckkc/ZWayMqttEndpoint#5]
Hey there,

I hope you may help: My MQTT commands are not executed by my Fibaro Wall Plug so far. Within zway it’s possible to switch it on/off perfectly. The Element ID in zway is: ZWayVDev_zway_2-0-37 (this is a wall plug/switch).

This is my configuration.yaml:

```
# Switch
switch:
  platform: mqtt
  name: "Lampe"
  state_topic: "zway/devices/zwayvdev_zway_2_0_37/update"
  command_topic: "zway/devices/zwayvdev_zway_2_0_37/set"
  payload_on: '{ "command": "on" }'
  payload_off: '{ "command": "off" }'
  optimistic: false
  qos: 0
  retain: true
  value_template: '{{ value_json.level }}'
```

In the app MQTT.fx the following packet will show up (but the switch won't react):

```
zway/devices/zwayvdev_zway_2_0_37/set
{ "command": "on" }
```

I would really appreciate any hints!

Thanks in advance
Marco

**Comment by kkckkc** [comment]
Hi

I'm away from home so will not be able to check in a few days. 

Anyhow, a couple of questions:

1. Do you see any messages on the state topic if you toggle the switch from zway - if not, there is probably some communication issue 

2. Do you see anything of interest in the zway log files. The mqtt integration should log incoming and outgoing messages (no payload thouh)


Regards
Magnus Johansson

**Comment by mny24** [comment]
Thanks for your quick reply!

> 1. Do you see any messages on the state topic if you toggle the switch from zway - if not, there is probably some communication issue

If toggled this message will appear:

```
{"id":"ZWayVDev_zway_2-0-37","title":"Fibaro Wall Plug","icon":"switch","type":"switchBinary","level":"on"}
```

> 2. Do you see anything of interest in the zway log files. The mqtt integration should log incoming and outgoing messages (no payload thouh)

```
[2016-05-24 21:40:01.233] [I] [core] ZwayMqttEndpoint: Status change message on topic zway/devices/zwayvdev_zway_2_0_37/set
[2016-05-24 21:40:01.234] [E] [core] Callback execution error: SyntaxError: Unexpected token O
    at Object.parse (native)
    at handleDeviceMessage (automation/modules/ZwayMqttEndpoint/index.js:381:28)
    at mqttClient.onmessage (automation/modules/ZwayMqttEndpoint/index.js:444:21)
    at null.callback (automation/modules/ZwayMqttEndpoint/index.js:40:22)
    at PacketStream.processBytes (automation/modules/ZwayMqttEndpoint/index.js:305:14)
    at tcp.sock.onrecv (automation/modules/ZwayMqttEndpoint/index.js:55:23)
[2016-05-24 21:40:21.231] [D] [zway] Job 0x13: deleted from queue

```

**Comment by kkckkc** [comment]
Ok, this means that the JSON payload cannot be parsed. I can see a few
potential reasons:

1. The JSON parser is quite sensitive - check to see if there are any weird
characters, like a hard space or something. Maybe try to remove all spaces

2. There is some error in the parsing of the MQTT message, causing the
payload not to be extracted correctly. What MQTT server are you using? I
haven't tried with the qos or retain flag set myself - maybe that triggers
some MQTT parsing bug. Try to remove the retain and qos flags and see if it
works better.



Regards
Magnus Johansson

**Comment by luxus** [comment]
i got pretty much the same error
![bildschirmfoto 2016-05-26 um 01 41 27](https://cloud.githubusercontent.com/assets/7449/15559510/2072a3ae-22e3-11e6-8bf8-7eb1ffc6be5a.png)
```
2016-05-25 23:41:13.884] [I] [core] ZwayMqttEndpoint: Status change message on topic zwaymqtt/devices/zwayvdev_zway_10_0_64/set
[2016-05-25 23:41:13.894] [E] [core] Callback execution error: SyntaxError: Unexpected token o
    at Object.parse (native)
    at handleDeviceMessage (automation/userModules/ZwayMqttEndpoint/index.js:381:28)
    at mqttClient.onmessage (automation/userModules/ZwayMqttEndpoint/index.js:444:21)
    at null.callback (automation/userModules/ZwayMqttEndpoint/index.js:40:22)
    at PacketStream.processBytes (automation/userModules/ZwayMqttEndpoint/index.js:305:14)
    at tcp.sock.onrecv (automation/userModules/ZwayMqttEndpoint/index.js:55:23)
```
server is mosquitto

**Comment by kkckkc** [comment]
I've pushed a change that should improve the logging in case of JSON parse
errors. Please try it out and let me know what you see in the logs.

**Comment by luxus** [comment]
i just update and restart z-way-server and it works

```

**Comment by luxus** [comment]
@mny24 payload should be something like this
```
    payload_on: '{ "command": "exact", "args": { "level": "on" } }'
    payload_off: '{ "command": "exact", "args": { "level": "off" } }'
```

**Comment by mny24** [comment]
Magnus & Kai,

thanks for your help! After updating I am able to switch on my Fibaro Wall Plug via the HA UI.

But: After the lamp switches on the switch on the HA web frontend will fall back to 'off'. I suppose HA does not realize the change of status being reported on MQTT.

My setting: Raspberry Pi, Razberry Z-Wave, Home Assistant, ZWayMqttEndpoint.

This is my command:

```
payload_on: '{ "command": "on" }'
payload_off: '{ "command": "off" }'
```

This is the MQTT.fx output:

```
zway/devices/zwayvdev_zway_2_0_37/set
{ "command": "on" }
```

And then:

```
zway/devices/zwayvdev_zway_2_0_37/update
{"id":"ZWayVDev_zway_2-0-37","title":"Fibaro Wall Plug","icon":"switch","type":"switchBinary","level":"on"}
```

Would be perfect to let HA know!

Many thanks
Marco

**Comment by kkckkc** [comment]
For my devices zway sends out three events during a second or so. So when I send

```
{ "command": "on" }
```

I get back (in rapid succession):

```
{ ... ,"type":"switchBinary","level":"on"}
{ ... ,"type":"switchBinary","level":"off"}
{ ..., "type":"switchBinary","level":"on"}
```

This means that in HA, the toggle switches back and forth a couple of times. Not sure if this is your exact problem though.

The coalesce functionality is supposed to fix this, but it is not working properly. There's a separate defect for this.

There is also the optimistic flag is HA that could be a possible workaround

**Comment by kkckkc** [comment]
Looking at my HA configuration I think your problem is that `value_template` must yield a value that exactly matches the `payload_on` and `payload_off`. In your example, `value_template` will yield a value of either `on` or `off`, but the payload is `{ "command": "on" }`. 

Below is a working example from my HA configuration. Notice the slightly more complicated `value_template` expression

```
switch:
- platform: mqtt
  name: 'Bedroom - Ceiling'
  state_topic: 'zway/devices/zwayvdev_zway_2_0_37/update'
  command_topic: 'zway/devices/zwayvdev_zway_2_0_37/set'
  payload_on: '{ "command":"on" }'
  payload_off: '{ "command":"off" }'
  value_template: '{ "command":"{{value_json.level}}" }'  
  optimistic: true 
```

**Comment by mny24** [comment]
It works!!! This is my configuration:

```
switch:
- platform: mqtt
  name: 'Lampe'
  state_topic: 'zway/devices/zwayvdev_zway_2_0_37/update'
  command_topic: 'zway/devices/zwayvdev_zway_2_0_37/set'
  payload_on: '{ "command":"on" }'
  payload_off: '{ "command":"off" }'
  value_template: '{ "command":"{{value_json.level}}" }'
  optimistic: false
```

THX
Marco
